# Generated by Django 3.2.16 on 2022-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('highest_edu', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=100)),
                ('year_of_completion', models.CharField(max_length=4)),
                ('current_organization', models.CharField(max_length=100)),
                ('current_rold', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('emp_type', models.CharField(max_length=20)),
            ],
        ),
    ]
