# Generated by Django 3.2.16 on 2022-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='current_rold',
            new_name='current_role',
        ),
        migrations.AlterField(
            model_name='formdata',
            name='date_of_joining',
            field=models.CharField(max_length=20),
        ),
    ]
